ractf/core

- src/authentication/basic_auth.py
- src/challenge/views.py
- src/hint/views.py
- src/member/serializers.py
- src/scorerecalculator/views.py
- src/team/views.py
- src/websockets/signals.py
have a gander at this lads, should work
> Individual Mode

- src/backend/mail.py
- src/backend/settings/production.py
This has not been tested as part of the project because I don't have an environment I can test it in. But the code added has been tested in an external file and works as intended.
> Add smtp mail support

- .github/workflows/build.yml
> Fix wording in docker container build

- src/config/config.py
- src/config/views.py
Currently, users can view individual config keys even when they are marked as sensitive.
> Patch low severity config vulnerability

- README.md
> Make the readme badn't

- README.md
Our own is a bit more reflective of who's done what
> Don't link to choojs's contributors list

- .github/workflows/docs.yml
- .github/workflows/test.yml
> Generate docs on all branches

- src/challenge/models.py
- src/challenge/serializers.py
- src/challenge/views.py
> make it a bit zoomier

- src/challenge/models.py
- src/challenge/serializers.py
- src/challenge/views.py
> Revert "make it a bit zoomier"

- src/backend/renderers.py
- src/config/config.py
This reverts commit 00943f261ca5bc61779fd20c37b58bf3b111fa4b.
> Revert "RACTF Chaos Program (#85)"

- src/challenge/models.py
- src/leaderboard/serializers.py
- src/leaderboard/tests.py
- src/leaderboard/urls.py
- src/leaderboard/views.py
- src/team/models.py
> Add matrix scoreboard endpoint

- .yakrazor/docker-compose.yml
- .yakrazor/yakrazor.json
Yakrazor works now, might aswell merge this
> Add yakrazor support

- .github/workflows/docs.yml
- .github/workflows/test.yml
- Dockerfile
- poetry.lock
- pyproject.toml
- src/backend/tests.py
- src/backend/views.py
> Python 3.9 Support

- src/challenge/views.py
> Better formatting for blood webhook

- src/backend/settings/__init__.py
This doesn't need a version bump as its just a change to default configs
> Make firstblood_webhook sensitive by default

- src/team/serializers.py
- src/team/views.py
should also make it a bit faster i think
> fix member count ordering

- src/backend/settings/__init__.py
<https://stackoverflow.com/questions/55367013/add-timestamp-and-username-to-log>
> Timestamp the logs

- src/leaderboard/views.py
> Remove BrowsableAPIRenderer from CTFTimeListView

- src/templates/2fa_removed.html
> Fix missing Django template end

- src/andromeda/views.py
> Block Andromeda instance requests if not in team

- src/authentication/providers.py
- src/authentication/tests.py
- src/team/serializers.py
- src/team/tests.py
Cleans up some missed cases from #237
> Fix handling of long or duplicate names

- README.md
> Document development environment setup and usage

- src/plugins/points/decay.py
- src/plugins/tests.py
> Fix negative points from decay plugin

- src/backend/permissions.py
- src/member/tests.py
> Fix POST requests slipping through AdminOrReadOnlyVisible
