src/backend/settings/production.py
Given that errors raised by Sentry will most likely come from client `docker-compose` setups, the issues themselves intrinsically don't require PII to fix. This PR disables sending PII to our Sentry environment.
=> Disable sending PII to Sentry

.coveragerc, .github/workflows/docs.yml, src/backend/settings/docs.py
This PR defines a new settings module, `backend.settings.docs`, which matches the old `backend.settings.test`. This means we don't need a database or redis just to generate the documentation.
=> Fix the Docs generation CI job

.github/workflows/build.yml
A new Docker image is pushed for every tag. Naturally, this means that tags
should likely be protected in the Repository settings somehow, unless
contributors are trusted.
In addition to the tagged Docker image push, the `latest` image is pushed on
every new tag.
=> Push Docker images on tags.

src/backend/pagination.py, src/backend/settings/__init__.py
Also removes the URL rewrite, this was necessary when we used to have broken url rewrite rules on nginx however this hasn't been the case for quite a while, and it assumed you were on a .co.uk domain, core has worked on domains that aren't .co.uk so this is fine to remove.
=> Rename FastPagination To FormattedPagination.

src/challenge/signals.py
We forgot Category exists. We've had 2 cache invalidation bugs recently, should probably improve the testing on it
=> Fix caching again

poetry.lock, pyproject.toml, src/backend/settings/__init__.py, src/challenge/views.py
Will send a small webhook message (if an env var is set) upon the first solve of each challenge
=> Add first blood webhook

src/member/models.py
This could also be fixed by making the max column length longer, I think this is a better solution because we'd end up having this caused by one exceptionally long user agent anyway.
=> Fix long user agents not being able to hit member self

src/challenge/serializers.py
Users can request instances of challenges that are locked through the andromeda api, thats a wontfix, but this hides the info so its basically impossible to do that now.
=> Hide cserv_name from challenge_metadata on locked challenges

src/challenge/signals.py
This should (hopefully) be the last challenge cache fix
=> Invalidate challenge cache on hint file and tag changes

Makefile, src/backend/settings/__init__.py, src/challenge/tests/test_views.py, src/challenge/views.py, src/ractf/management/commands/create_preevent_cache.py, src/sockets/signals.py
Some more caching and optimisations to lighten the load of the first few minutes of the ctf.
todo:
=> Start of event optimisations

docker-compose.yml, entrypoints/backend.sh, entrypoints/sockets.sh, src/stats/apps.py, src/stats/signals.py, src/stats/views.py
This makes changes to the existing solve and attempt count metrics to add
labels. This will likely break existing monitoring dashboards, but allows us to
be more granular in the solves (correct flag submissions) and attempts
(incorrect flag submissions) by challenge and category, whilst still allowing to
sum the total amount of flags via PromQL.
Caching of the values is removed. The values are moved to counters, which work
sanely in multiprocess mode in contrast to gauge mode. What we trade off for
this is the ability to decrease solve count, but after development discussions,
we have concluded that we currently do not really care about this use case.
A new metric for the total amount of points scored is introduced. As with the
updated metrics above, this is a counter. This does not allow …
=> Prometheus statistics improvements & additions.

src/authentication/providers.py, src/authentication/tests.py
This was removed for some reason in #73
=> Fix email regex

.github/workflows/integrate.yml, .github/workflows/test.yml, Makefile, docker-compose.yml
This Pull Request adds integrations tests in GitHub Actions, which perform the following:
- Boot up backend using the image from GitHub Container Registry
- Wait 10 seconds for the boot
- Use `make fake-data` to generate some test fixtures
- Shut down the containers
- Boot up the containers on the current branch
- Wait 10 seconds for the boot
- Confirm that the `/stats/stats/` endpoint works
To do this, I've had to add a persistent database to the `postgres` container, but I've updated the `clean-dev-server` makefile target to clean this up. This is tested within the workflow.
This should hopefully catch things like us writing broken migrations or updating things like twisted which prevent core from booting.
Resolves #238
=> Add Integration Tests

src/backend/settings/__init__.py
This was changed to default to true in django 4.0 and throws a warning.
=> Remove unnecessary setting causing a warning

src/authentication/basic_auth.py, src/authentication/providers.py, src/authentication/views.py, src/team/serializers.py
PR #245 updated the validators to check for duplicate usernames and
emails by running a query before posting the data. Let's rely on the
database indexes instead, which is more robust. This builds on top of
PR #245's tests to verify the functionality.
=> Rely on database unique constraints

src/backend/settings/__init__.py, src/backend/settings/lint.py
This was causing issues in environments where the `EMAIL_PROVIDER` environments variable wasn't being set because a settings module was already configuring it.
=> Keep emails enabled when envvar missing

src/ractf/management/commands/create_user.py
I'm not sure why we were setting `nargs` and `const`. Setting `required` seems much more sensible.
Resolves #260
=> Fix create_user command

.gitignore, src/admin/tests.py, src/challenge/models.py, src/challenge/tests/test_models.py
Resolves #191 (not a bug, the error is correct).
This also swaps the existing health check tests to `assertIn` so they don't break as we add more health checks.
=> Add a Health Check for Broken Freeform Challenges

src/andromeda/tests.py, src/andromeda/views.py, src/backend/settings/__init__.py
Resolves #267
This is a little messy as it needs to handle old environments where we
didn't require explicitly setting this.
It also has the worst test I've written in a while, but this should
bring coverage up a bit.
=> Move enabling challenge server to settings

src/plugins/flag/plaintext.py, src/plugins/tests.py
=> Fix pre event check only checking start of flag

src/admin/models.py
`os.getlogin()` fails if not running from a TTY. We should handle that so commands don't fail under most environments.
Resolves #286
=> Handle missing TTY

.github/workflows/docs.yml, .github/workflows/test.yml, Dockerfile
Builds are currently broken as we refer to the old install script (which Poetry have broken to make you stop using it). This patch puts us onto the new one and fixes things.
=> Update to the new Poetry install script

.github/workflows/integrate.yml, scripts/fake/__init__.py, scripts/fake/__main__.py, scripts/fake/config.py
The `auditlog` table is marked as `logged` in Postgres, so it can't have foreign key references to unlogged tables. To speed up test fixture generation, we disable Postgres logging.
This patch adds `auditlog` to the list of tables we disable logging on and makes disabling logging optional.
=> Disable Postgres logging during tests for new table
